#ifndef MACRO_H
#define MACRO_H

#define POLL_ENGINE_UPOLL  0x00
#define POLL_ENGINE_EPOLL  0x01
#define POLL_ENGINE_KQUEUE 0x02
#define POLL_ENGINE_EVPORT 0x04

#define PLATFORM_UNIX    0x00
#define PLATFORM_LINUX   0x10
#define PLATFORM_FREEBSD 0x20
#define PLATFORM_OPENBSD 0x21
#define PLATFORM_NETBSD  0x22
#define PLATFORM_DARWIN  0x30
#define PLATFORM_SOLARIS 0x40

#if PLATFORM == PLATFORM_LINUX
#define POLL_ENGINE POLL_ENGINE_EPOLL
#elif PLATFORM >= PLATFORM_FREEBSD && PLATFORM <= PLATFORM_DARWIN
#define POLL_ENGINE POLL_ENGINE_KQUEUE
#elif PLATFORM == PLATFORM_SOLARIS
#define POLL_ENGINE POLL_ENGINE_EVPORT
#else
#define POLL_ENGINE POLL_ENGINE_UPOLL
#endif

#endif
